USE [hurtownia]
GO
DELETE FROM t_word
INSERT INTO t_word(Province, Word_Name, CityName) VALUES
('dolnoslaskie','WORD Jelenia Gora','Glogow'),
('dolnoslaskie','WORD Jelenia Gora','Kamienna Gora'),
('dolnoslaskie','WORD Jelenia Gora','Milicz'),
('dolnoslaskie','WORD Wroclaw','Wroclaw'),
('dolnoslaskie','WORD Wroclaw','Olesnica'),
('dolnoslaskie','WORD Wroclaw','Olawa'),
('dolnoslaskie','WORD Walbrzych','Walbrzych'),
('dolnoslaskie','WORD Walbrzych','Swidnica'),
('dolnoslaskie','WORD Jelenia Gora','Jelenia Gora'),
('dolnoslaskie','WORD Legnica','Legnica'),
('dolnoslaskie','WORD Legnica','Luban'),
('dolnoslaskie','WORD Legnica','Lubin'),
('dolnoslaskie','WORD Jelenia Gora','Boleslawiec'),
('dolnoslaskie','WORD Walbrzych','Klodzko'),
('kujawsko-pomorskie','WORD Wloclawek','Wloclawek'),
('kujawsko-pomorskie','WORD Torun','Torun'),
('kujawsko-pomorskie','WORD Torun','Grudziadz'),
('kujawsko-pomorskie','WORD Bydgoszcz','Bydgoszcz'),
('kujawsko-pomorskie','WORD Bydgoszcz','Inowroclaw'),
('lubelskie','WORD Zamosc','Bilgoraj'),
('lubelskie','WORD Biala Podlaska','Biala Podlaska'),
('lubelskie','WORD Biala Podlaska','Lukow'),
('lubelskie','WORD Lublin','Lublin'),
('lubelskie','WORD Lublin','Pulawy'),
('lubelskie','WORD Lublin','Krasnik'),
('lubelskie','WORD Chelm','Chelm'),
('lubelskie','WORD Zamosc','Zamosc'),
('lubuskie','WORD Zielona Gora','Zielona Gora'),
('lubuskie','WORD Gorzow','Gorzow Wielkopolski'),
('mazowieckie','WORD Plock','Sochaczew'),
('mazowieckie','WORD Radom','Grojec'),
('mazowieckie','WORD Radom','Radom - Radomskiego'),
('mazowieckie','WORD Ostroleka','Ostroleka'),
('mazowieckie','WORD Ciechanow','Ciechanow'),
('mazowieckie','WORD Radom','Radom'),
('mazowieckie','WORD Plock','Plock'),
('mazowieckie','WORD Radom','Zwolen'),
('mazowieckie','WORD Warszawa','Warszawa - Odlewnicza'),
('mazowieckie','WORD Radom','Kozienice'),
('mazowieckie','WORD Warszawa','Warszawa - Bemowo'),
('mazowieckie','WORD Warszawa','Warszawa - Radarowa'),
('mazowieckie','WORD Siedlce','Garwolin'),
('mazowieckie','WORD Siedlce','Siedlce'),
('mazowieckie','WORD Ciechanow','Mlawa'),
('malopolskie','MORD Krakow','Krakow - Nowohucka'),
('malopolskie','MORD Nowy Sacz','Nowy Targ'),
('malopolskie','MORD Krakow','Krakow - Balicka'),
('malopolskie','MORD Krakow','Oswiecim'),
('malopolskie','MORD Nowy Sacz','Nowy Sacz'),
('malopolskie','MORD Tarnow','Tarnow'),
('opolskie','WORD Opole','Kedzierzyn Kozle'),
('opolskie','WORD Opole','Nysa'),
('opolskie','WORD Opole','Opole'),
('podkarpackie','WORD Tarnobrzeg','Tarnogrzeg'),
('podkarpackie','WORD Rzeszow','Rzeszow'),
('podkarpackie','WORD Krosno','Krosno'),
('podkarpackie','WORD Przemysl','Przemysl'),
('podlaskie','WORD Suwalki','Suwalki'),
('podlaskie','WORD Lomza','Lomza'),
('podlaskie','WORD Bialystok','Bialystok'),
('podlaskie','Bialystok','Bielsk Podlaski'),
('pomorskie','WORD Slupsk','Slupsk'),
('pomorskie','PORD Gdansk','Gdansk'),
('pomorskie','PORD Gdansk','Gdynia'),
('slaskie','WORD Czestochowa','Czestochowa'),
('slaskie','WORD Bielsko Biala','Bielsko Biala'),
('slaskie','WORD Katowice','Katowice'),
('slaskie','WORD Katowice','Dabrowa Gornicza'),
('slaskie','WORD Katowice','Bytom'),
('slaskie','WORD Katowice','Jastrzebie Zdroj'),
('slaskie','WORD Katowice','Tychy'),
('slaskie','WORD Katowice','Rybnik'),
('swietokrzyskie','WORD Kielce','Kielce'),
('swietokrzyskie','WORD Kielce','Ostrowiec Swietokrzyski'),
('warminsko-mazurskie','WORD Elblag','Elblag'),
('warminsko-mazurskie','WORD Olsztyn','Olsztyn'),
('wielkopolskie','WORD Konin','Konin'),
('wielkopolskie','WORD Kalisz','Kalisz'),
('wielkopolskie','WORD Pila','Pila'),
('wielkopolskie','WORD Poznan','Poznan'),
('wielkopolskie','WORD Leszno','Leszno'),
('zachodniopomorskie','ZORD Koszalin','Szczecinek'),
('zachodniopomorskie','ZORD Koszalin','Koszalin'),
('zachodniopomorskie','WORD Szczecin','Szczecin'),
('zachodniopomorskie','WORD Szczecin','Barlinek'),
('lodzkie','WORD Lodz','Lodz - Maratonska'),
('lodzkie','WORD Sieradz','Sieradz'),
('lodzkie','WORD Lodz','Lodz - Smutna'),
('lodzkie','WORD Skierniewice','Skierniewice'),
('lodzkie','WORD Piotrkow','Piotrkow Trybunalski')